### ISSUE TITLE
No install 4.3.1

### ISSUE THREAD

**Issue by momon** [kayako/wordpress-integration#8]
The plugin will not install.  I uploaded the "kayako" dir to WP version 4.3.1 and it does not show up in the plugins list.  I also tried ziping the dir and uploading it via the wp admin interface and it throws an error saying it can't install.

Thanks!

**Comment by nidhigupta-22** [comment]
Hello Momon,

Thanks for pointing the issue, we have worked upon it and made it compatible with WordPress 4.3.1.
You can download the updated module and let us know how it goes.

Thanks & Regards,
Nidhi Gupta
